# Generated by Django 3.2.6 on 2021-08-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('heading', models.CharField(max_length=200)),
                ('news', models.CharField(max_length=1200)),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
    ]
