# Generated by Django 3.2.6 on 2021-08-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='picture',
            field=models.ImageField(null=True, upload_to='news/'),
        ),
    ]
