# Generated by Django 3.2.6 on 2021-08-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_news_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='tags',
            new_name='name',
        ),
    ]
