# Generated by Django 3.2.6 on 2021-08-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_rename_tags_news_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='click',
            field=models.IntegerField(null=True),
        ),
    ]
