# Generated by Django 3.2.6 on 2021-09-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0005_alter_news_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
