# Generated by Django 3.2.6 on 2021-09-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readMore', '0002_auto_20210925_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='info',
            field=models.IntegerField(null=True),
        ),
    ]
