# Generated by Django 3.2.6 on 2021-08-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessID', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=90)),
                ('password', models.CharField(max_length=64)),
                ('number', models.IntegerField(max_length=14)),
                ('address', models.CharField(max_length=128)),
                ('post', models.CharField(max_length=20)),
            ],
        ),
    ]
