# Generated by Django 3.2.6 on 2021-08-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210820_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='picture',
            field=models.ImageField(null=True, upload_to='Profile Pictures/'),
        ),
    ]
