# Generated by Django 3.2.6 on 2021-08-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_data_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='picture',
            field=models.ImageField(null=True, upload_to='ProfilePictures/'),
        ),
    ]
