# Generated by Django 3.2.6 on 2021-08-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_data_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='picture',
        ),
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
